### ISSUE TITLE
非常棒的图片选择器，发现几个问题

### ISSUE THREAD

**Issue by RondaHe** [zhangyu9050/UUPhotoActionSheet#2]
1、拍照有时点击没反应，看了源码，是拍照那个button选中后的处理有问题
2、如果有照片流，默认是先加载照片流里地照片到actionsheet中。自以为用相机胶卷的更好。
3、actionsheet中的照片顺序应该和相册中的相反更好，参照微信一样

**Comment by amoylong** [comment]
把UUAssetManager.m内的

**Comment by amoylong** [comment]
- (void)getPhotoListOfGroup:(ALAssetsGroup *)alGroup result:(void (^)(NSArray *))result{
  
  _assetPhotos = [[NSMutableArray alloc] init];
  [alGroup setAssetsFilter:[ALAssetsFilter allPhotos]];
  [alGroup enumerateAssetsUsingBlock:^(ALAsset *alPhoto, NSUInteger index, BOOL *stop) {
  
  ```
  if(alPhoto == nil){
  
      result(_assetPhotos);
      return;
  }
  ```

//        [_assetPhotos addObject:alPhoto];
        [_assetPhotos insertObject:alPhoto atIndex:0];
    }];
}
注释部分改为下面这样那个就快要达到相反效果，不过相册里面也会相应变成相反的就是了

**Comment by zhangyu9050** [comment]
图片排序问题考虑到使用习惯，以最新的排在最前面，所以是insert
